name: CrashPayment
version: 1.0.1
main: net.crashcraft.crashpayment.CrashPayment
website: http://Crashcraft.net
loadbefore: []
description: A core that can crash
depend: []
softdepend: [Vault, PlaceholderAPI]
api-version: 1.16